global:
  scrape_interval: 5s  # seberapa sering Prometheus menarik data dari target

scrape_configs:
  - job_name: 'model_inference_monitoring'
    static_configs:
      - targets: ['localhost:8000']
