name: Train Model with MLflow & DagsHub

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  train-model:
    runs-on: ubuntu-latest

    env:
      MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
      MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
      MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}

    steps:
      - name: ðŸ“¥ Checkout repository
        uses: actions/checkout@v3

      - name: ðŸ Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: ðŸ“¦ Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r Membangun_model/requirements.txt
          pip install --upgrade dagshub>=0.3.10  # âœ… Wajib untuk auth.login

      - name: ðŸš€ Run training script
        run: |
          python Membangun_model/modelling.py

      - name: ðŸ“‚ Upload trained model artifact
        uses: actions/upload-artifact@v3
        with:
          name: trained-model
          path: Membangun_model/model.pkl
