name: CI for ML Project

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Membangun_model/requirements.txt
          pip install dagshub==0.3.15

      - name: Run modelling.py (training + log ke MLflow)
        run: |
          python Membangun_model/modelling.py
        env:
          MLFLOW_TRACKING_URI: https://dagshub.com/AkasSakti/Eksperimen_SML_Akas-Bagus-Setiawan2.mlflow
          MLFLOW_TRACKING_TOKEN: ${{ secrets.MLFLOW_TRACKING_TOKEN }}
          DAGSHUB_ACCESS_TOKEN: ${{ secrets.MLFLOW_TRACKING_TOKEN }}

      - name: Run automate_Akas.py pipeline
        run: |
          python preprocessing/automate_Akas.py
        env:
          MLFLOW_TRACKING_URI: https://dagshub.com/AkasSakti/Eksperimen_SML_Akas-Bagus-Setiawan2.mlflow
          MLFLOW_TRACKING_TOKEN: ${{ secrets.MLFLOW_TRACKING_TOKEN }}
          DAGSHUB_ACCESS_TOKEN: ${{ secrets.MLFLOW_TRACKING_TOKEN }}

      - name: Run inference check (optional)
        run: |
          python "Monitoring dan Logging/7.Inference.py" --model_path Membangun_model/model.pkl
        continue-on-error: true
