name: Train Model and Log to DagsHub

on:
  push:
    paths:
      - 'Membangun_model/**'   # Trigger kalau ada perubahan di folder Membangun_model
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r Membangun_model/requirements.txt

    - name: Run training script with MLflow authentication
      env:
        MLFLOW_TRACKING_URI: https://dagshub.com/AkasSakti/Eksperimen_SML_Akas-Bagus-Setiawan2.mlflow
        MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
        MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}
      run: python Membangun_model/modelling.py

    - name: Upload training artifacts (optional)
      uses: actions/upload-artifact@v4
      with:
        name: training-artifacts
        path: Membangun_model/Membangun_model/
